declare module "lucide-react" {
  import { FC, SVGProps } from "react"
  export type IconNode = [string, Record<string, string>][]
  export type LucideIcon = FC<SVGProps<SVGSVGElement>>
  export const createLucideIcon: (name: string, iconNode: IconNode) => LucideIcon
  export const icons: Record<string, LucideIcon>
  export const Activity: LucideIcon
  export const AlertCircle: LucideIcon
  export const AlertTriangle: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowRight: LucideIcon
  export const BarChart3: LucideIcon
  export const BookOpen: LucideIcon
  export const BrainCircuit: LucideIcon
  export const Check: LucideIcon
  export const CheckCircle: LucideIcon
  export const CheckCircle2: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ChevronUp: LucideIcon
  export const ClipboardList: LucideIcon
  export const Clock: LucideIcon
  export const Copy: LucideIcon
  export const Download: LucideIcon
  export const Edit2: LucideIcon
  export const Edit3: LucideIcon
  export const Expand: LucideIcon
  export const ExternalLink: LucideIcon
  export const Eye: LucideIcon
  export const FileEdit: LucideIcon
  export const Files: LucideIcon
  export const FileOutput: LucideIcon
  export const FileText: LucideIcon
  export const Filter: LucideIcon
  export const FlaskConical: LucideIcon
  export const GripVertical: LucideIcon
  export const Layers: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const Lightbulb: LucideIcon
  export const ListChecks: LucideIcon
  export const Loader2: LucideIcon
  export const Lock: LucideIcon
  export const LogOut: LucideIcon
  export const Mail: LucideIcon
  export const Maximize2: LucideIcon
  export const Menu: LucideIcon
  export const Minimize2: LucideIcon
  export const MoreHorizontal: LucideIcon
  export const Network: LucideIcon
  export const PenTool: LucideIcon
  export const PieChart: LucideIcon
  export const Play: LucideIcon
  export const Plus: LucideIcon
  export const Quote: LucideIcon
  export const RefreshCw: LucideIcon
  export const Rocket: LucideIcon
  export const RotateCcw: LucideIcon
  export const Save: LucideIcon
  export const Scissors: LucideIcon
  export const Search: LucideIcon
  export const Settings: LucideIcon
  export const Shield: LucideIcon
  export const Shrink: LucideIcon
  export const Sparkles: LucideIcon
  export const Square: LucideIcon
  export const Star: LucideIcon
  export const StopCircle: LucideIcon
  export const Target: LucideIcon
  export const Trash2: LucideIcon
  export const TrendingUp: LucideIcon
  export const User: LucideIcon
  export const X: LucideIcon
  export const Zap: LucideIcon
}
